# Generated by Django 4.0.5 on 2022-06-24 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('short_url', '0005_shorturl_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shorturl',
            name='pub_date',
            field=models.DateTimeField(verbose_name='date'),
        ),
    ]
