# Generated by Django 4.0.5 on 2022-06-14 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GroceryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_description', models.CharField(max_length=200, verbose_name='item description')),
                ('date_created', models.DateField(verbose_name='date created')),
                ('date_complete', models.DateField(verbose_name='date completed')),
                ('shop_complete', models.BooleanField()),
            ],
        ),
    ]
