# Generated by Django 4.0.5 on 2022-06-15 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocerylist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groceryitem',
            name='date_complete',
            field=models.DateField(blank=True, null=True, verbose_name='date completed'),
        ),
        migrations.AlterField(
            model_name='groceryitem',
            name='shop_complete',
            field=models.BooleanField(default=False),
        ),
    ]
