# Generated by Django 4.0.5 on 2022-06-14 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery_list', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groceryitem',
            name='date_fulfilled',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date fulfilled'),
        ),
    ]
