# Generated by Django 4.0.5 on 2022-06-21 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Urlshort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ourl', models.CharField(max_length=300)),
                ('surl', models.CharField(max_length=51)),
                ('num_clicked', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
