# Generated by Django 4.0.5 on 2022-06-22 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlshortener', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlshort',
            name='ourl',
            field=models.URLField(max_length=300),
        ),
    ]
