# Generated by Django 4.0.5 on 2022-06-24 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chirp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='body',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
