# Generated by Django 4.1 on 2022-08-05 19:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chirp', '0004_chirp_delete_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chirp',
            name='chirpname',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chirp', to=settings.AUTH_USER_MODEL),
        ),
    ]
