# Generated by Django 4.0.6 on 2022-07-18 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlshortener_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlshort',
            name='short_url',
            field=models.CharField(max_length=20),
        ),
    ]
