# Generated by Django 4.0.5 on 2022-06-17 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groceries', '0002_alter_groceryitem_completed_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grocery_Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('created_date', models.DateTimeField(verbose_name='created date')),
                ('completed_date', models.DateTimeField(blank=True, null=True)),
                ('complete', models.BooleanField()),
            ],
        ),
        migrations.DeleteModel(
            name='GroceryItem',
        ),
    ]
