# Generated by Django 4.0.5 on 2022-06-19 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grocery_list', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='groceryitem',
            old_name='created_data',
            new_name='created_date',
        ),
    ]
