# Generated by Django 4.0.5 on 2022-07-06 11:22

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('grocery_list', '0002_rename_created_data_groceryitem_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groceryitem',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 6, 11, 22, 48, 470517, tzinfo=utc)),
        ),
    ]
