# Generated by Django 4.0.5 on 2022-07-06 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery_list', '0004_alter_groceryitem_completed_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groceryitem',
            name='created_date',
            field=models.DateField(null=True),
        ),
    ]
