# Generated by Django 4.0.5 on 2022-07-06 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery_list', '0007_alter_groceryitem_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groceryitem',
            name='complete',
            field=models.BooleanField(default=False),
        ),
    ]
