# Generated by Django 4.0.5 on 2022-06-16 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UrlChoppa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=255)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('url_code', models.CharField(max_length=6)),
                ('ip_addy', models.CharField(max_length=50)),
            ],
        ),
    ]
