# Generated by Django 4.0.5 on 2022-08-08 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='posts',
            options={'ordering': ['-created']},
        ),
        migrations.AlterField(
            model_name='posts',
            name='title',
            field=models.TextField(max_length=50),
        ),
        migrations.AlterField(
            model_name='posts',
            name='updated_last',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
