# Generated by Django 4.0.5 on 2022-06-14 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GroceryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_text', models.CharField(max_length=255)),
                ('create_date', models.DateTimeField(verbose_name='date created')),
                ('complete_date', models.DateTimeField(blank=True, null=True, verbose_name='date completed')),
                ('is_completed', models.BooleanField(default=False)),
            ],
        ),
    ]
