# Generated by Django 4.0.5 on 2022-06-21 01:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('short_url', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shorturlcode',
            name='create_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
