# Generated by Django 4.0.5 on 2022-06-27 23:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0002_alter_twiddle_twiddle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twiddle',
            name='twiddle',
            field=models.TextField(max_length=50),
        ),
        migrations.AlterField(
            model_name='twiddle',
            name='twiddler',
            field=models.ForeignKey(max_length=200, on_delete=django.db.models.deletion.CASCADE, related_name='twiddles', to=settings.AUTH_USER_MODEL),
        ),
    ]
