# Generated by Django 4.0.5 on 2022-06-14 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery_list', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groceryitem',
            name='date_completed',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date completed'),
        ),
        migrations.AlterField(
            model_name='groceryitem',
            name='date_created',
            field=models.DateTimeField(verbose_name='Date created'),
        ),
        migrations.AlterField(
            model_name='groceryitem',
            name='grocery_text',
            field=models.CharField(max_length=50, verbose_name='Grocery item'),
        ),
        migrations.AlterField(
            model_name='groceryitem',
            name='is_complete',
            field=models.BooleanField(verbose_name='Competed'),
        ),
    ]
