# Generated by Django 4.0.5 on 2022-06-15 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery_list', '0002_alter_groceryitem_date_completed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groceryitem',
            name='is_complete',
            field=models.BooleanField(verbose_name='Completed'),
        ),
    ]
