# Generated by Django 4.0.5 on 2022-06-15 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery_list', '0003_alter_groceryitem_is_complete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groceryitem',
            name='is_complete',
            field=models.BooleanField(default=False, verbose_name='Completed'),
        ),
    ]
