# Generated by Django 4.0.5 on 2022-06-14 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab1', '0002_groceryitem_date_completed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groceryitem',
            name='append_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
