# Generated by Django 4.0.6 on 2022-07-05 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('url_shortener', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='urlshortener',
            old_name='num',
            new_name='code',
        ),
    ]
