# Generated by Django 4.0.5 on 2022-06-13 22:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Glist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('glist_text', models.CharField(max_length=50)),
                ('cdate', models.DateField(verbose_name='date created')),
                ('comdate', models.DateField(verbose_name='date to be completed')),
            ],
        ),
        migrations.CreateModel(
            name='Gitem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_text', models.CharField(max_length=50)),
                ('item_num', models.IntegerField()),
                ('glist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='groceries.glist')),
            ],
        ),
    ]
