# Generated by Django 4.0.5 on 2022-06-22 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groceries', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gitem',
            old_name='status',
            new_name='cstatus',
        ),
        migrations.AlterField(
            model_name='gitem',
            name='comdate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
