# Generated by Django 4.0.6 on 2022-07-18 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_rename_students_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='capstone',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
    ]
