# Generated by Django 4.0.5 on 2022-06-13 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocerylist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groceryitem',
            name='date_completed',
            field=models.DateTimeField(blank=True, null=True, verbose_name='completed'),
        ),
        migrations.AlterField(
            model_name='groceryitem',
            name='is_done',
            field=models.BooleanField(blank=True, null=True, verbose_name='is complete'),
        ),
    ]
