# Generated by Django 4.0.5 on 2022-06-13 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocerylist', '0002_alter_groceryitem_date_completed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groceryitem',
            name='description',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='groceryitem',
            name='is_done',
            field=models.BooleanField(default=False, verbose_name='is complete'),
        ),
    ]
