# Generated by Django 4.0.5 on 2022-06-22 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('short_url', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shorturl',
            old_name='short_url',
            new_name='small_url',
        ),
    ]
