# Generated by Django 4.0.5 on 2022-06-23 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('short_url', '0002_rename_short_url_shorturl_small_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shorturl',
            name='long_url',
            field=models.URLField(),
        ),
    ]
