# Generated by Django 4.0.5 on 2022-06-23 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('short_url', '0003_alter_shorturl_long_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shorturl',
            name='id',
        ),
        migrations.AlterField(
            model_name='shorturl',
            name='small_url',
            field=models.CharField(editable=False, max_length=5, primary_key=True, serialize=False),
        ),
    ]
