# Generated by Django 4.0.5 on 2022-06-24 00:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('short_url', '0006_alter_shorturl_pub_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shorturl',
            name='pub_date',
        ),
    ]
