# Generated by Django 4.0.6 on 2022-08-05 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mygympal', '0003_alter_blog_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='body',
            field=models.TextField(max_length=1000),
        ),
    ]
