# Generated by Django 4.0.5 on 2022-06-15 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='URLShortener',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taken_url', models.URLField(max_length=500)),
                ('given_url', models.URLField(max_length=500)),
            ],
        ),
    ]
