# Generated by Django 4.0.5 on 2022-06-27 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShortURL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_url', models.URLField(max_length=10000)),
                ('new_url', models.CharField(max_length=100)),
            ],
        ),
    ]
