# Generated by Django 4.0.6 on 2022-07-21 21:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pokemon', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='caught_by',
            field=models.ManyToManyField(blank=True, related_name='caught', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='image_back',
            field=models.URLField(unique=True),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='image_front',
            field=models.URLField(unique=True),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='number',
            field=models.IntegerField(unique=True),
        ),
    ]
