# Generated by Django 4.0.6 on 2022-07-22 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0002_alter_pokemon_caught_by_alter_pokemon_image_back_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='image_back',
            field=models.URLField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='image_front',
            field=models.URLField(null=True, unique=True),
        ),
    ]
