# Generated by Django 4.0.6 on 2022-07-22 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0003_alter_pokemon_image_back_alter_pokemon_image_front'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='image_back',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='image_front',
            field=models.URLField(),
        ),
    ]
