# Generated by Django 4.0.5 on 2022-06-15 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grocery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groceryitem',
            name='pub_date',
            field=models.DateTimeField(verbose_name='Date of purchase'),
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manage_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='grocery.groceryitem')),
            ],
        ),
    ]
