# Generated by Django 4.0.5 on 2022-06-13 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grocery', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='votes',
            new_name='got_item',
        ),
    ]
