# Generated by Django 4.0.5 on 2022-06-15 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grocery', '0002_alter_groceryitem_pub_date_choice'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Choice',
            new_name='ItemChoice',
        ),
    ]
