# Generated by Django 4.0.5 on 2022-06-15 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grocery', '0003_rename_choice_itemchoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemchoice',
            name='manage_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decide', to='grocery.groceryitem'),
        ),
    ]
