# Generated by Django 4.0.5 on 2022-06-15 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery', '0005_alter_itemchoice_manage_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemchoice',
            name='item_amount',
            field=models.IntegerField(default=0),
        ),
    ]
