# Generated by Django 4.0.5 on 2022-06-15 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grocery', '0006_itemchoice_item_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groceryitem',
            name='store_items',
        ),
        migrations.RemoveField(
            model_name='itemchoice',
            name='item_amount',
        ),
    ]
