# Generated by Django 4.0.5 on 2022-06-15 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery', '0007_remove_groceryitem_store_items_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemchoice',
            name='selected',
            field=models.IntegerField(default=0),
        ),
    ]
