# Generated by Django 4.0.5 on 2022-06-13 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GroceryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(max_length=50)),
                ('date_created', models.DateTimeField(verbose_name='date created')),
                ('status', models.BooleanField(verbose_name='status')),
                ('date_fulfilled', models.DateTimeField(verbose_name='date fulfilled')),
            ],
        ),
    ]
