# Generated by Django 4.0.6 on 2022-07-17 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=200)),
                ('l_name', models.CharField(max_length=200)),
                ('cohort', models.CharField(max_length=200)),
                ('fav_topic', models.CharField(max_length=200)),
                ('fav_teacher', models.CharField(max_length=200)),
                ('capstone', models.URLField(help_text='student capstone project URL')),
            ],
        ),
    ]
